# Embed the MSL kernel into the binary as a C array.
#
# Why: newLibraryWithSource: has no include mechanism, and the offline Metal
# compiler (xcrun metal) ships only with full Xcode — not the Command Line
# Tools — so a build-time .metallib would silently add an Xcode requirement
# to a zero-dependency project. Instead we inline kernel_types.h into the
# shader source here and compile it at runtime (~100 ms, once, at startup).
#
# Run via: cmake -DTYPES=... -DKERNEL=... -DOUT=... -P embed_msl.cmake

file(READ "${TYPES}" types_src)
file(READ "${KERNEL}" kernel_src)
string(REPLACE "#include \"kernel_types.h\"" "${types_src}" kernel_src
               "${kernel_src}")

# Hex-array emission: immune to raw-string delimiter collisions.
string(HEX "${kernel_src}" hex)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")

# unsigned char: the source contains UTF-8 comment bytes > 127, which
# won't narrow into a signed char array.
file(WRITE "${OUT}"
     "// Generated by cmake/embed_msl.cmake - do not edit.\n"
     "static const unsigned char pt_msl_source[] = {${hex}0x00};\n")
